name: deploy

on: [push, pull_request]

jobs:
  pages:
    name: "cloudflare pages (node: ${{ vars.NODE_VERSION || '18' }})"
    runs-on: ubuntu-latest
    if: ${{ vars.USE_CLOUDFLARE_PAGES == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ vars.NODE_VERSION || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || '18' }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build project
        run: yarn build
      - name: Export project
        run: yarn export
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
