name: reviewdog

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION || 18 }}

jobs:
  eslint:
    name: 'eslint (node: ${{ env.NODE_VERSION }})'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
          eslint_flags: '--ext .js,.jsx,.ts,.tsx .'
  stylelint:
    name: 'stylelint (node: ${{ env.NODE_VERSION }})'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
          stylelint_input: 'src/**/*.css src/**/*.vue'
  prettier:
    name: 'prettier (node: ${{ env.NODE_VERSION }})'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
  tsc:
    name: 'tsc (node: ${{ env.NODE_VERSION }})'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
  actionlint:
    name: 'actionlint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
