name: reviewdog

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  eslint:
    name: "eslint (node: ${{ vars.NODE_VERSION || '18' }})"
    runs-on: ubuntu-latest
    if: ${{ vars.USE_REVIEWDOG == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ vars.NODE_VERSION || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || '18' }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
          eslint_flags: '--ext .js,.jsx,.ts,.tsx .'
  stylelint:
    name: "stylelint (node: ${{ vars.NODE_VERSION || '18' }})"
    runs-on: ubuntu-latest
    if: ${{ vars.USE_REVIEWDOG == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ vars.NODE_VERSION || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || '18' }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
          stylelint_input: 'src/**/*.css src/**/*.vue'
  prettier:
    name: "prettier (node: ${{ vars.NODE_VERSION || '18' }})"
    runs-on: ubuntu-latest
    if: ${{ vars.USE_REVIEWDOG == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ vars.NODE_VERSION || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || '18' }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
  tsc:
    name: "tsc (node: ${{ vars.NODE_VERSION || '18' }})"
    runs-on: ubuntu-latest
    if: ${{ vars.USE_REVIEWDOG == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node v${{ vars.NODE_VERSION || '18' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION || '18' }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    if: ${{ vars.USE_REVIEWDOG == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: 'github-check'
          filter_mode: 'nofilter'
          fail_on_error: true
